
#Display All Orders Using a nested loop, print the entire order table row by row so that each order’s details are displayed clearly.

orders = [ ["ORD001","Laptop",75000,"Completed"], ["ORD002","Mouse",500,"Completed"], ["ORD003","Laptop",75000,"Returned"], ["ORD004","Keyboard",1500,"Completed"], ["ORD005","Laptop",75000,"Completed"], ["ORD006","Monitor",20000,"Fraud"], ["ORD007","Mouse",500,"Completed"], ["ORD008","Laptop",75000,"Completed"] ]

print("Display All Orders")

for order in orders:
	print(order)

#Detect Suspicious Activity The system suspects fraud when: the same product appears more than 3 times, OR an order has status "Fraud"

print("Suspicious Orders")

suspicious_order = []
products = []
suspicious_product = []

total = 0

for order in orders:
	products.append(order[1])

for product in products:
	if products.count(product) > 3 and product not in suspicious_product:
		suspicious_product.append(product)

for order in orders:
	if order[1] in suspicious_product or order[3] is "Fraud":
		if order not in suspicious_order:
			suspicious_order.append(order)

print(suspicious_order)

#Calculate Total Revenue Only Completed orders contribute to revenue. Write code that: iterates through the dataset adds the price of all completed orders prints the total revenue generated for the day.
print("Total Revenue")

total = 0

for order in orders:
	if order[3] is "Completed":
		total = total + order[2]

print(total)

#Count Order Types Using loops and conditional statements, count how many orders fall into each category:

print("Count of Order Types")

order_types_all = []
order_types = []
order_types_counts = []

for order in orders:
	order_types_all.append(order[3])

print(order_types_all)

for order_type in order_types_all:
	if order_type not in order_types:
		order_types.append(order_type)

print(order_types)

for order_type in order_types:
	order_types_counts.append([order_type,order_types_all.count(order_type)])

print("Order Types with Counts")
print(order_types_counts)

#Generate a List of Unique Products Create a new list containing unique product names present in the dataset. You must implement this without using the set() function.
products = []

for order in orders:
	if order[1] not in products:
		products.append(order[1])

print("Products List")
print(products)

#Product Sales Analysis For each unique product, determine: how many times it was ordered total revenue generated by that product This requires nested loops.

#### Use the unique product list from above ####

sales_data = []

for product in products:
	total = 0
	count = 0
	for order in orders:
		if order[1] == product:
			total = order[2] + total
			count = count + 1
	sales_data.append([product,count,total])

	print(sales_data)

#Identify the Most Sold Product Based on the frequency of orders, determine which product appears the most in the dataset.
products_all = []
product_count = []

for order in orders:
	products_all.append(order[1])

print("All Products")
print(products_all)

for product in products_all:
	if product not in products:
		products.append(product)

print("Products")
print(products)

for product in products:
		product_count.append([product,products_all.count(product)])

max = 0
max_sold_product = []

for product in product_count:
	if max_sold_product:
		if product[1] > max:
			max = product[1]
			max_sold_product.pop()
			max_sold_product.append(product)
	else:
		max = product[1]
		max_sold_product.append(product)

print("Max sold product")
print(max_sold_product)

#Remove Fraud Orders Create a cleaned dataset by removing orders whose status is "Fraud". Use list methods to store the cleaned data in a new list.

cleaned = []

for order in orders:
	if order[3] is not "Fraud":
		cleaned.append(order)

print("Cleaned Orders of Fraud")
for order in cleaned:
	print(order)